# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8099/api/v1/messages
Accept: application/json

### POST message
POST http://localhost:8099/api/v1/messages
Content-Type: application/json

{
  "message": "hello",
  "sender": "Jay LU",
  "time": "2019-03-31T09:58:32.900Z"
}

###
